version: "3.9"
volumes:
  postgres_data:
    driver: local

services:

  postgres:
    container_name: postgresdb-container
    # image: templategithubactionspostgresql
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: pw123
    # volumes:
    #   - type: volume
    #     source: postgresdb-container
    #     target: /var/lib/postgresql/data
    ports:
      - "5432:5432"

  keycloak:
    container_name: keycloak-container
    depends_on:
      - postgres
    image: quay.io/keycloak/keycloak:latest
    # image: templategithubactionskeycloak
    command:
      # - start-dev
      - start-dev --spi-login-protocol-openid-connect-legacy-logout-redirect-uri=true
      - -Dkeycloak.migration.strategy=IGNORE_EXISTING
    ports:
      - 8080:8080
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: jojo
      KEYCLOAK_PASSWORD: pw123
      KEYCLOAK_LOGLEVEL: DEBUG
      ROOT_LOGLEVEL: DEBUG
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_IMPORT: /tmp/my-realm.json
      # KEYCLOAK_LOGLEVEL: DEBUG
      PROXY_ADDRESS_FORWARDING: 'true'
      KEYCLOAK_FRONTEND_URL: https://proxy/auth
      # DB_USER: keycloak
      # DB_PASSWORD: pw123
      # DB_ADDR: postgres
    # volumes:
    #   - type: volume
    #     source: keycloak-volume
    #     target: /opt/jboss/keycloak/standalone/data
    #   - type: bind
    #     source: ./keycloak/my-realm.json
    #     target: /tmp/my-realm.json

  angular:
    container_name: angular-container
    image: templategithubactionsangular
    build:
      context: app-angular-keycloak
      # dockerfile: docker/Dockerfile.angular
    command: sh -c "cd app-angular-keycloak && npm link @angular/cli && ng serve --port 4200 --host 0.0.0.0"
    # command: ng serve
    # command: sh -c "ls -a"
    # command: sh -c "npm i && cd app-angular-keycloak && ng serve"'
    ports: 
      - 4200:4200

  angular2:
    container_name: angular2-container
    image: templategithubactionsangular2
    build:
      context: angulartestapp
      # context: app-angular-keycloak
      # dockerfile: docker/Dockerfile.angular
    command: sh -c "cd angulartestapp && npm link @angular/cli && ng serve --port 4567 --host 0.0.0.0"
    # command: sh -c "cd app-angular-keycloak && npm link @angular/cli && ng serve --host 0.0.0.0"
    # command: ng serve
    # command: sh -c "ls -a"
    # command: sh -c "npm i && cd app-angular-keycloak && ng serve"'
    ports: 
      - 4567:4567
  