# syntax=docker/dockerfile:1

FROM node:18-alpine

# WORKDIR /app
WORKDIR /angulartestapp/src/app
# WORKDIR /

ENV PATH /angulartestapp/node_modules/.bin:$PATH

COPY ./angulartestapp/package.json ./
COPY ./angulartestapp/package-lock.json ./
RUN npm install

COPY . .

