# syntax=docker/dockerfile:1
FROM node:18-alpine

# WORKDIR /app
WORKDIR /app-angular-keycloak/src/app
# WORKDIR /

ENV PATH /app-angular-keycloak/node_modules/.bin:$PATH

COPY ./app-angular-keycloak/package.json ./
COPY ./app-angular-keycloak/package-lock.json ./
RUN npm install

COPY . .
